GET http://localhost:5000/api/v1/user/fdfdfdđff

###
POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json 

{
    "userName": "Odin",
    "email": "Odin@gmail.com",
    "password": "123456"
}

###
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json 

{
    "userName": "Blade",
    "email": "Blade@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/api/v1/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImVtYWlsIjoiQmxhZGVAZ21haWwuY29tIiwicm9sZV9jb2RlIjoiUjEiLCJpYXQiOjE2Njc1NDU4MjgsImV4cCI6MTY2Nzk3NzgyOH0.2mIgBaZXzAFnrcv-jWL7XNA4zFhucfwZREiGLjzP2Cg
###
GET http://localhost:5000/api/v1/insert/

###
GET http://localhost:5000/api/v1/book/

###
GET http://localhost:5000/api/v1/book/?name=The Passion

###
GET http://localhost:5000/api/v1/book/?order[]=price&order[]=ASC&limit=3

###
GET http://localhost:5000/api/v1/book/?available[]=5&available[]=10


//File này chạy được vì đã cài file REST Client ở phần tiện ích mở rộng